#!/bin/bash
gcc -Wall -Wextra -pedantic -Werror -O2 -c ../csources/polar.c
gcc -Wall -Wextra -pedantic -Werror -O2 -c ../csources/r3util.c  
gcc -c composepol.c

gcc composepol.o polar.o r3util.o -o composepol -lm

rm *.o
