#!/bin/bash
tmp=$(mktemp)
idBoat="imoca_60_foils"

cat > "$tmp" <<'JQ'
.["data_" + $boat][0] as $b
| ($b.twa)  as $twa
| ($b.tws)  as $tws
| ($b.sail[] | select(.name == $sail) | .speed) as $spd
| (["twa"] + $tws) as $header
| [$header] + ( $twa | to_entries | map([.value] + ($spd[.key] // [])) )
| map(join(";")) | join("\n")
JQ

jq -r --arg boat "$idBoat" '.["data_" + $boat][0].sail[].name' "$1" | while read -r SAIL; do
  jq -r --arg sail "$SAIL" --arg boat $idBoat -f "$tmp" "$1" > "$idBoat${SAIL}.csv"
  echo "Write: $idBoat${SAIL}.csv"
done
rm -f "$tmp"

