#!/bin/bash
CFLAGS="-Wall -Wextra -Wpedantic -Wformat=2 -Wwrite-strings -Wredundant-decls -Wmissing-include-dirs -Wnested-externs -O2"
gcc $CFLAGS -c aisgps.c `pkg-config --cflags glib-2.0`
gcc $CFLAGS -Wno-format-nonliteral -c ../csources/r3util.c
gcc $CFLAGS -c aisgpsserver.c `pkg-config --cflags glib-2.0`

gcc aisgpsserver.o r3util.o aisgps.o -o aisgpsserver -std=c11 -lm `pkg-config --cflags --libs glib-2.0`
rm -f *.o
