#!/bin/bash
CFLAGS_PERF="-Wall -Wextra -Wpedantic -Wformat=2 -Wwrite-strings -Wredundant-decls -Wmissing-include-dirs -Wnested-externs -O3 -g -pg"
CFLAGS="-Wall -Wextra -Wpedantic -Wformat=2 -Wwrite-strings -Wredundant-decls -Wmissing-include-dirs -Wnested-externs -O3"
gcc $CFLAGS -c -march=native -ffast-math -fno-math-errno -fno-trapping-math engine.c
gcc $CFLAGS -c r3grib.c
gcc $CFLAGS -c polar.c
gcc $CFLAGS -c common.c
gcc $CFLAGS -c -Wno-format-nonliteral r3util.c
gcc $CFLAGS -c readgriballwithouteccodes.c
gcc $CFLAGS -c -march=native -ffast-math -fno-math-errno -fno-trapping-math option.c
gcc $CFLAGS -c  capi.c

#gcc $CFLAGS capi.o r3util.o r3grib.o readgriballwithouteccodes.o polar.o engine.o option.o common.o -o capi -lm -leccodes 
gcc $CFLAGS capi.o r3util.o r3grib.o readgriballwithouteccodes.o polar.o engine.o option.o common.o -o capi -lm -leccodes 
rm -f *.o
mv capi ../.

