#!/bin/bash
CFLAGS="-Wall -Wextra -Wpedantic -Wformat=2 -Wwrite-strings -Wredundant-decls -Wmissing-include-dirs -Wnested-externs -O2"
gcc $CFLAGS -c -O3 engine.c
gcc $CFLAGS -c r3grib.c
gcc $CFLAGS -c polar.c
gcc $CFLAGS -Wno-format-nonliteral -c r3util.c
gcc $CFLAGS -c readgriballwithouteccodes.c
gcc $CFLAGS -c option.c
gcc $CFLAGS -c routing.c

gcc routing.o option.o r3util.o r3grib.o readgriballwithouteccodes.c polar.o engine.o -o routing -lm -leccodes
rm -f *.o
mv routing ../.



